name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build-and-push:
    permissions:
      packages: write
      contents: read
      
    runs-on: ubuntu-latest

    steps:
    
    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
        
    - name: Build & Push the Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: eric-jxl/weibo:latest
        platforms: linux/amd64,linux/arm64/v8


        run: |
          docker build . --file Dockerfile --tag eric-jxl/weibo:$(date +%s)
          docker push eric-jxl/weibo:$(date +%s)

