name: Docker Image CI

on:
  push:
    paths:  
      - "*.py"
      - "Dockerfile"

jobs:

  build-and-push:
    permissions:
      packages: write
      contents: read
      
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Get Git commit hash
      run: echo "GIT_COMMIT_SHA=${{ github.sha }}" >> $GITHUB_ENV

    - name: Get current date and time
      run: echo "TIMESTAMP=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
      
    - name: Tag Docker image with commit SHA and timestamp
      uses: docker/build-push-action@v3
      with:
        context: .
        push: false
        tags: |
          ghcr.io/${{ github.repository }}:${{ env.GIT_COMMIT_SHA }}
          ghcr.io/${{ github.repository }}:${{ env.TIMESTAMP }}
    
    - name: 'Build and push with Buildx'
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          ghcr.io/${{ github.repository }}:${{ env.GIT_COMMIT_SHA }}
          ghcr.io/${{ github.repository }}:${{ env.TIMESTAMP }}
          ghcr.io/${{ github.repository }}:latest
