name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build-and-push:
    permissions:
      packages: write
      contents: read
      
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
        
    - name: Build & Push the Docker image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/eric-jxl/weibo:$(date +%s)
        docker push ghcr.io/eric-jxl/weibo:$(date +%s)

